# Generated by Django 5.1.1 on 2024-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_profile_user_id_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, to='articles.article'),
        ),
    ]
