# Generated by Django 5.1.1 on 2024-11-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_profile_saved_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
    ]
