# Generated by Django 5.1.1 on 2024-11-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_author_article_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='email',
        ),
    ]
